### ISSUE TITLE
null

### ISSUE THREAD

**Issue by openainext** [superRaytin/xss-filter#2]

**Comment by superRaytin** [comment]
没看出你指的是什么问题... 😂

**Comment by wanglong167** [comment]
var xssFilter = require('xssfilter');
var xssfilter = new xssFilter();

var output = xssfilter.filter('https://github.com/superRaytin/xss-filter/blob/master/README-CN.md?test=1');
// output: https://github.com/superRaytin/xss-filter/blob/master/README-CN.md? test=1 
结果会在test前面加个空格

**Comment by superRaytin** [comment]
xssFilter 是针对 HTML 代码段，不是 URL...

**Comment by wanglong167** [comment]
html片段里面没url吗。。。
var output = xssfilter.filter('<a href="https://github.com/superRaytin/xss-filter/blob/master/README-CN.md?test=1">a</a>'); 
算了你就当我没问
